//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BDRestauranteProyectoLenguajesEntities : DbContext
    {
        public BDRestauranteProyectoLenguajesEntities()
            : base("name=BDRestauranteProyectoLenguajesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Administrador> Administrador { get; set; }
        public virtual DbSet<Cliente> Cliente { get; set; }
        public virtual DbSet<EstadoOrden> EstadoOrden { get; set; }
        public virtual DbSet<HistoricoCambioEstadoOrden> HistoricoCambioEstadoOrden { get; set; }
        public virtual DbSet<LineaOrden> LineaOrden { get; set; }
        public virtual DbSet<Orden> Orden { get; set; }
        public virtual DbSet<Party> Party { get; set; }
        public virtual DbSet<Plato> Plato { get; set; }
        public virtual DbSet<UsuarioCocina> UsuarioCocina { get; set; }
    }
}
